using UnityEngine;

namespace Scripts.Stats
{
    [System.Serializable]
    public enum Stat
    {
        MAX_HEALTH = 1000,

        MOVEMENT_WALK_SPEED = 1100,
        MOVEMENT_SPRINT_SPEED = 1101,
        MOVEMENT_CROUCH_SPEED = 1102,
        MOVEMENT_GROUND_ACCELERATION = 1110,
        MOVEMENT_AIR_ACCELERATION = 1111,
        MOVEMENT_GROUND_FRICTION = 1112,
        MOVEMENT_AIR_CONTROL = 1113,
        MOVEMENT_GRAVITY = 1120,
        MOVEMENT_JUMP_SPEED = 1121,
        MOVEMENT_COYOTE_TIME = 1122,
        MOVEMENT_JUMP_BUFFER_TIME = 1123,
        MOVEMENT_STAND_HEIGHT = 1130,
        MOVEMENT_CROUCH_HEIGHT = 1131,
        MOVEMENT_CAPSULE_RADIUS = 1132,
        MOVEMENT_SLOPE_LIMIT = 1140,
        MOVEMENT_STEP_HEIGHT = 1141,
        MOVEMENT_SKIN_WIDTH = 1142,
        MOVEMENT_SPRINT_FORWARD_DOT = 1150,
        MOVEMENT_SPRINT_SIDE_MULTIPLIER = 1151,
        MOVEMENT_SPRINT_BACK_MULTIPLIER = 1152,

        DAMAGE = 2000
    }
}
