using UnityEngine;

namespace Scripts.Stats
{
    [System.Serializable]
    public enum Stat
    {
        MAX_HEALTH = 1000,

        MOVEMENT_WALK_SPEED = 1100,
        MOVEMENT_SPRINT_SPEED = 1101,
        MOVEMENT_CROUCH_SPEED = 1102,
        MOVEMENT_GROUND_ACCELERATION = 1110,
        MOVEMENT_AIR_ACCELERATION = 1111,
        MOVEMENT_GROUND_FRICTION = 1112,
        MOVEMENT_AIR_CONTROL = 1113,
        MOVEMENT_GRAVITY = 1120,
        MOVEMENT_JUMP_SPEED = 1121,
        MOVEMENT_COYOTE_TIME = 1122,
        MOVEMENT_JUMP_BUFFER_TIME = 1123,
        MOVEMENT_STAND_HEIGHT = 1130,
        MOVEMENT_CROUCH_HEIGHT = 1131,
        MOVEMENT_CAPSULE_RADIUS = 1132,
        MOVEMENT_SLOPE_LIMIT = 1140,
        MOVEMENT_STEP_HEIGHT = 1141,
        MOVEMENT_SKIN_WIDTH = 1142,
        MOVEMENT_SPRINT_FORWARD_DOT = 1150,
        MOVEMENT_SPRINT_SIDE_MULTIPLIER = 1151,
        MOVEMENT_SPRINT_BACK_MULTIPLIER = 1152,

        WEAPON_PRIMARY_DAMAGE = 2000,
        WEAPON_PRIMARY_RANGE = 2001,
        WEAPON_PRIMARY_FIRE_INTERVAL = 2002,
        WEAPON_PRIMARY_MAGAZINE_SIZE = 2003,
        WEAPON_PRIMARY_RESERVE_AMMO = 2004,
        WEAPON_PRIMARY_RELOAD_TIME = 2005,
        WEAPON_PRIMARY_SPREAD_DEGREES = 2006,

        WEAPON_PISTOL_DAMAGE = 2100,
        WEAPON_PISTOL_RANGE = 2101,
        WEAPON_PISTOL_FIRE_INTERVAL = 2102,
        WEAPON_PISTOL_MAGAZINE_SIZE = 2103,
        WEAPON_PISTOL_RESERVE_AMMO = 2104,
        WEAPON_PISTOL_RELOAD_TIME = 2105,
        WEAPON_PISTOL_SPREAD_DEGREES = 2106
    }
}
